// generated by "sampctl package init"
#include <a_samp>
#include <Actor_Plus>
#include <sscanf2>
#include <zcmd>

new actor;
main() {
	actor = CreateActor(21, 129.9311,-71.6216,1.5781,153.7815);
	HelloWorld();
}

public OnPlayerConnect(playerid) {
	SetSpawnInfo(playerid, 0, 21, 129.9311,-71.6216,1.5781,153.7815, 0, 0, 0, 0, 0, 0);
	return 1;
}

CMD:fala(playerid, params[]) {
	new str[244];
	if(sscanf(params, "s[244]", str))
		return 0;
	SetActorChatBubble(actor, str, 3000);
	return 1;
}

CMD:toggle(playerid) {
	TogglePlayerTargetActor(playerid, 1);
	return 1;
}

CMD:untoggle(playerid) {
	TogglePlayerTargetActor(playerid, 0);
	return 1;
}

public OnPlayerTargetActor(const playerid, const actorid) {
	new str[244];
	format(str, sizeof(str), "Target actor %d", actorid);
	SendClientMessage(playerid, -1, str);
	return 1;
}
