// generated by "sampctl package init"
#include <a_samp>
#include <zcmd>
#include "Actor_Plus.inc"

main() 
{
}

new actor;
public OnGameModeInit() {
	HelloWorld();
	actor = CreateActor(21, 129.9311,-71.6216,1.5781,153.7815);
	return 1;
}

public OnPlayerSpawn(playerid) {
	TogglePlayerTargetActor(playerid, 1);
	SetPlayerPos(playerid, 129.9311+5.0,-71.6216,1.5781);
	return 1;
}

CMD:actor(playerid) {
	SetActorChatBubble(actor, "Hmm tu e?", 3000);
	return 1;
}


public OnPlayerTargetActor(const playerid, const actorid) {
	new str[200];
	format(str, sizeof(str), "Voce mirou no actor %d", actorid);
	SendClientMessage(playerid, -1, str);
	return 1;
}

