// generated by "sampctl package init"
#include <a_samp>
#include "include.inc"

main() 
{
}

public OnGameModeInit() {
	new actor = CreateActor(21, 129.9311,-71.6216,1.5781,153.7815);
	SetActorChatBubble(actor, "Ola pohaaaa");
	return 1;
}

public OnPlayerSpawn(playerid) {
	SetPlayerPos(playerid, 129.9311,-71.6216,1.5781);
	return 1;
}
